version: "3.5"

services:
  shinyproxy:
    build: ./shinyproxy
    expose:
      - 8080
    networks:
      sp-net:
        ipv4_address: 172.16.199.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/:/opt/shinyproxy/container-logs/
  nginx:
    image: nginx:1.17.5
    restart: unless-stopped
    ports:
      - 3868:80
    networks:
      sp-net:
        ipv4_address: 172.16.199.4
    depends_on:
      - shinyproxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  sp-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.199.0/24
